"""Service name catalog for SMS classification.

CORE_SERVICE_ALIASES maps common aliases to canonical display names. The
additional catalog extends exact phrase matching for less-specialized services.
Keep this file data-only so service detection logic remains easy to audit.
"""

CORE_SERVICE_ALIASES = {
    "google": "Google", "gmail": "Google", "g.co": "Google", "google pay": "Google Pay", "gpay": "Google Pay",
    "google voice": "Google Voice", "google ads": "Google Ads", "youtube": "YouTube", "yt": "YouTube",
    "whatsapp": "WhatsApp", "wa": "WhatsApp", "telegram": "Telegram", "tg": "Telegram",
    "facebook": "Facebook", "fb": "Facebook", "meta": "Facebook", "messenger": "Facebook Messenger",
    "instagram": "Instagram", "ig": "Instagram", "threads": "Threads",
    "twitter": "Twitter", "x": "Twitter", "x.com": "Twitter", "tiktok": "TikTok", "douyin": "Douyin",
    "microsoft": "Microsoft", "outlook": "Microsoft", "hotmail": "Microsoft", "live.com": "Microsoft", "office 365": "Microsoft 365",
    "apple": "Apple", "icloud": "Apple", "app store": "Apple", "apple id": "Apple",
    "amazon": "Amazon", "aws": "Amazon Web Services", "prime video": "Prime Video", "amazon pay": "Amazon Pay",
    "paypal": "PayPal", "stripe": "Stripe", "wise": "Wise", "revolut": "Revolut", "venmo": "Venmo", "cash app": "Cash App", "cashapp": "Cash App",
    "netflix": "Netflix", "spotify": "Spotify", "linkedin": "LinkedIn", "snapchat": "Snapchat", "discord": "Discord",
    "uber": "Uber", "uber eats": "Uber Eats", "lyft": "Lyft", "grab": "Grab", "bolt": "Bolt", "careem": "Careem", "didi": "DiDi",
    "openai": "OpenAI", "chatgpt": "OpenAI", "claude": "Claude", "anthropic": "Anthropic", "gemini": "Gemini",
    "binance": "Binance", "coinbase": "Coinbase", "kraken": "Kraken", "bybit": "Bybit", "okx": "OKX", "kucoin": "KuCoin",
    "steam": "Steam", "epic games": "Epic Games", "riot": "Riot Games", "roblox": "Roblox", "twitch": "Twitch",
    "tinder": "Tinder", "bumble": "Bumble", "hinge": "Hinge", "badoo": "Badoo", "grindr": "Grindr",
    "line": "LINE", "wechat": "WeChat", "weixin": "WeChat", "viber": "Viber", "signal": "Signal", "kakao": "KakaoTalk", "kakaotalk": "KakaoTalk",
    "yahoo": "Yahoo", "protonmail": "Proton Mail", "proton": "Proton", "tutanota": "Tuta", "tuta": "Tuta", "yandex": "Yandex", "vk": "VK",
    "shein": "SHEIN", "shopee": "Shopee", "lazada": "Lazada", "aliexpress": "AliExpress", "temu": "Temu", "ebay": "eBay",
    "paytm": "Paytm", "phonepe": "PhonePe", "mobikwik": "MobiKwik", "bkash": "bKash", "nagad": "Nagad", "rocket": "Rocket",
    "samsung": "Samsung", "xiaomi": "Xiaomi", "oneplus": "OnePlus", "oppo": "OPPO", "vivo": "Vivo", "huawei": "Huawei", "realme": "Realme",
    "airbnb": "Airbnb", "booking": "Booking.com", "booking.com": "Booking.com", "agoda": "Agoda", "expedia": "Expedia",
    "klarna": "Klarna", "afterpay": "Afterpay", "affirm": "Affirm", "tabby": "Tabby", "tamara": "Tamara",
    "capcut": "CapCut", "shein": "SHEIN", "temu": "Temu", "noon": "Noon", "talabat": "Talabat",
    "hungerstation": "HungerStation", "careem": "Careem", "noon food": "Noon Food", "swiggy": "Swiggy", "zomato": "Zomato",
    "razorpay": "Razorpay", "paystack": "Paystack", "flutterwave": "Flutterwave", "mercadopago": "Mercado Pago",
    "pix": "Pix", "truemoney": "TrueMoney", "momo": "MoMo", "dana": "DANA", "ovo": "OVO",
    "pubg": "PUBG Mobile", "pubg mobile": "PUBG Mobile", "free fire": "Free Fire", "garena": "Garena",
    "supercell": "Supercell", "clash of clans": "Clash of Clans", "clash royale": "Clash Royale",
    "mobile legends": "Mobile Legends", "valorant": "Valorant", "league of legends": "League of Legends",
    "snapdeal": "Snapdeal", "meesho": "Meesho", "nykaa": "Nykaa", "bigbasket": "BigBasket", "blinkit": "Blinkit",
    "zepto": "Zepto", "instamart": "Instamart", "dunzo": "Dunzo", "rapido": "Rapido", "porter": "Porter",
    "cred": "Cred", "groww": "Groww", "zerodha": "Zerodha", "upstox": "Upstox", "angel one": "Angel One",
    "etoro": "eToro", "webull": "Webull", "robinhood": "Robinhood", "fidelity": "Fidelity",
    "adobe": "Adobe", "canva": "Canva", "figma": "Figma", "notion": "Notion", "slack": "Slack", "zoom": "Zoom",
    "datadog": "Datadog", "sentry": "Sentry", "vercel": "Vercel", "netlify": "Netlify", "cloudflare": "Cloudflare",
    "shopify": "Shopify", "woocommerce": "WooCommerce", "square": "Square", "squareup": "Square",
    "doordash": "DoorDash", "grubhub": "Grubhub", "postmates": "Postmates", "instacart": "Instacart",
    "lyft": "Lyft", "ola": "Ola", "in drive": "inDrive", "indrive": "inDrive", "yandex go": "Yandex Go",
    "gett": "Gett", "free now": "FREE NOW", "freenow": "FREE NOW", "mytaxi": "FREE NOW",
    "signal": "Signal", "imo": "imo", "zalo": "Zalo", "kik": "Kik", "textnow": "TextNow",
    "proton": "Proton", "proton mail": "Proton Mail", "tutanota": "Tuta", "mail ru": "Mail.ru",
    "aliexpress": "AliExpress", "alibaba": "Alibaba", "1688": "1688", "wish": "Wish", "joom": "Joom",
    "fedex": "FedEx", "ups": "UPS", "dhl": "DHL", "usps": "USPS", "aramex": "Aramex", "delhivery": "Delhivery",
    "ticketmaster": "Ticketmaster", "bookmyshow": "BookMyShow", "eventbrite": "Eventbrite",
    "splitwise": "Splitwise", "venmo": "Venmo", "zelle": "Zelle", "cash app": "Cash App",
    "nubank": "Nubank", "inter": "Banco Inter", "itau": "Itaú", "santander": "Santander",
    "hsbc": "HSBC", "barclays": "Barclays", "chase": "Chase", "wells fargo": "Wells Fargo",
    "hdfc": "HDFC Bank", "icici": "ICICI Bank", "sbi": "SBI", "axis bank": "Axis Bank",
    "jio": "Jio", "airtel": "Airtel", "vodafone": "Vodafone", "verizon": "Verizon", "tmobile": "T-Mobile",
    "t mobile": "T-Mobile", "att": "AT&T", "at t": "AT&T", "orange": "Orange", "ooredoo": "Ooredoo",
    "etisalat": "Etisalat", "stc": "STC", "du": "Du", "mtn": "MTN", "safaricom": "Safaricom",
}

COMMON_SERVICE_NAMES = (
    "Google", "Gmail", "YouTube", "Google Pay", "Google Voice", "Google Ads", "Google Cloud", "Google Workspace",
    "WhatsApp", "Telegram", "Facebook", "Facebook Messenger", "Instagram", "Threads", "TikTok", "Twitter", "X", "Snapchat",
    "LinkedIn", "Pinterest", "Reddit", "Discord", "Twitch", "Tumblr", "Quora", "Medium", "Substack", "Mastodon",
    "Microsoft", "Outlook", "Hotmail", "Microsoft 365", "OneDrive", "Teams", "Skype", "Xbox", "Bing", "Azure",
    "Apple", "iCloud", "Apple ID", "App Store", "Apple Pay", "Apple Music", "FaceTime", "iMessage", "TestFlight", "Find My",
    "Amazon", "Amazon Pay", "AWS", "Prime Video", "Twitch", "Audible", "Kindle", "Alexa", "Amazon Music", "IMDb",
    "PayPal", "Stripe", "Wise", "Revolut", "Venmo", "Cash App", "Zelle", "Skrill", "Neteller", "Payoneer", "Remitly", "WorldRemit",
    "Visa", "Mastercard", "American Express", "Discover", "Western Union", "MoneyGram", "N26", "Monzo", "Chime", "Varo",
    "Binance", "Coinbase", "Kraken", "Bybit", "OKX", "KuCoin", "Crypto.com", "Gemini", "Bitstamp", "Bitfinex", "Gate.io", "MEXC",
    "Netflix", "Spotify", "Disney Plus", "Hulu", "HBO Max", "Max", "Peacock", "Paramount Plus", "Apple TV", "Prime Video",
    "SoundCloud", "Deezer", "Tidal", "Pandora", "iHeartRadio", "TuneIn", "Shazam", "Anghami", "JioSaavn", "Gaana",
    "Uber", "Uber Eats", "Lyft", "Bolt", "Grab", "Gojek", "DiDi", "Careem", "Ola", "Yandex Go", "inDrive", "BlaBlaCar",
    "DoorDash", "Deliveroo", "Foodpanda", "Zomato", "Swiggy", "Just Eat", "Glovo", "Talabat", "Wolt", "Rappi", "Postmates", "Grubhub",
    "Airbnb", "Booking.com", "Expedia", "Agoda", "Tripadvisor", "Hotels.com", "Vrbo", "Skyscanner", "Kayak", "Trip.com",
    "Steam", "Epic Games", "Riot Games", "Roblox", "PlayStation", "Nintendo", "EA", "Ubisoft", "Battle.net", "GOG", "Minecraft", "Garena",
    "Tinder", "Bumble", "Hinge", "Badoo", "OkCupid", "Match", "Plenty of Fish", "Grindr", "Happn", "Coffee Meets Bagel",
    "LINE", "WeChat", "Viber", "Signal", "KakaoTalk", "Kik", "imo", "Zalo", "Truecaller", "TextNow", "TextMe", "Talkatone",
    "Yahoo", "AOL", "Proton Mail", "Tuta", "Yandex", "Mail.ru", "GMX", "Zoho Mail", "Fastmail", "Mailchimp", "SendGrid", "Twilio",
    "OpenAI", "ChatGPT", "Anthropic", "Claude", "Gemini", "Perplexity", "Copilot", "Hugging Face", "Midjourney", "Runway",
    "GitHub", "GitLab", "Bitbucket", "Docker", "NPM", "PyPI", "Cloudflare", "DigitalOcean", "Heroku", "Vercel", "Netlify", "Render",
    "Shopify", "WooCommerce", "Magento", "BigCommerce", "Squarespace", "Wix", "WordPress", "GoDaddy", "Namecheap", "Hostinger",
    "eBay", "Etsy", "AliExpress", "Alibaba", "Temu", "SHEIN", "Shopee", "Lazada", "Rakuten", "Mercado Libre", "Flipkart", "Myntra",
    "Walmart", "Target", "Best Buy", "Costco", "IKEA", "Home Depot", "Lowe's", "Nike", "Adidas", "Zara", "H&M", "Uniqlo",
    "Paytm", "PhonePe", "MobiKwik", "Freecharge", "BHIM", "Razorpay", "Cashfree", "Instamojo", "CCAvenue", "Pine Labs",
    "bKash", "Nagad", "Rocket", "Upay", "JazzCash", "EasyPaisa", "GCash", "Maya", "OVO", "DANA", "GoPay", "ShopeePay",
    "M-Pesa", "Airtel Money", "MTN Mobile Money", "Orange Money", "Wave", "PalmPay", "OPay", "Paga", "Kuda", "Moniepoint",
    "Bank of America", "Chase", "Wells Fargo", "Citi", "Capital One", "US Bank", "PNC", "TD Bank", "Truist", "HSBC",
    "Barclays", "NatWest", "Lloyds", "Santander", "Revolut Bank", "Starling Bank", "Scotiabank", "RBC", "BMO", "CIBC",
    "HDFC Bank", "ICICI Bank", "SBI", "Axis Bank", "Kotak", "IDFC First", "Yes Bank", "Canara Bank", "Union Bank", "Punjab National Bank",
    "Samsung", "Xiaomi", "OnePlus", "OPPO", "Vivo", "Huawei", "Realme", "Nokia", "Motorola", "Sony", "LG", "Lenovo",
    "Slack", "Zoom", "Dropbox", "Box", "Notion", "Airtable", "Asana", "Trello", "Monday", "ClickUp", "Jira", "Confluence",
    "Salesforce", "HubSpot", "Zendesk", "Intercom", "Freshdesk", "ServiceNow", "Workday", "BambooHR", "DocuSign", "Adobe",
    "Canva", "Figma", "Miro", "Lucidchart", "Grammarly", "Duolingo", "Coursera", "Udemy", "edX", "Khan Academy", "Quizlet", "Chegg",
    "Indeed", "Glassdoor", "Upwork", "Fiverr", "Freelancer", "Toptal", "PeoplePerHour", "Naukri", "Bayt", "ZipRecruiter",
    "FedEx", "UPS", "DHL", "USPS", "Royal Mail", "DPD", "Hermes", "Evri", "Aramex", "Blue Dart", "Delhivery", "J&T Express",
    "OpenTable", "Yelp", "Foursquare", "Eventbrite", "Ticketmaster", "StubHub", "SeatGeek", "Meetup", "Patreon", "Ko-fi", "Buy Me a Coffee",
    "Robinhood", "eToro", "TradingView", "Webull", "Fidelity", "Charles Schwab", "E-Trade", "Interactive Brokers", "Nubank", "PicPay",
    "Coursera", "Udacity", "Skillshare", "MasterClass", "Codecademy", "DataCamp", "Pluralsight", "LinkedIn Learning", "Babbel", "Busuu",
    "Headspace", "Calm", "Strava", "Fitbit", "MyFitnessPal", "Peloton", "Garmin", "Nike Run Club", "HealthifyMe", "Noom",
    "T-Mobile", "Verizon", "AT&T", "Vodafone", "Airtel", "Jio", "Orange", "MTN", "Ooredoo", "Etisalat", "Du", "STC",
    "Netflix Games", "Crunchyroll", "Funimation", "Viki", "Hotstar", "JioCinema", "SonyLIV", "ZEE5", "iQIYI", "Bilibili",
    "Craigslist", "OLX", "Carousell", "Vinted", "Depop", "Poshmark", "StockX", "GOAT", "Farfetch", "ASOS", "Noon", "Trendyol",
)

# Regional and vertical catalogs are intentionally flat data. Combined with
# generated spelling variants in service_detector.py, this gives over 1000
# maintained aliases without embedding matching rules here.
REGIONAL_SERVICE_NAMES = (
    "Acko", "Adyen", "Affirm", "Afterpay", "Airtable", "Airtel Thanks", "Al Rajhi Bank", "Alfamart", "Alipay", "Allegro",
    "Almosafer", "Amazon Flex", "Amtrak", "Angel One", "Apollo 24/7", "Apple Bank", "Arab Bank", "Aramex", "ASB Bank", "ASOS",
    "Bajaj Finserv", "Banco do Brasil", "Banco Inter", "Banco Santander", "Bank Mandiri", "Bank Rakyat Indonesia", "Bank Syariah Indonesia", "Bankera", "Banorte", "BCA",
    "BDO", "Bershka", "Bet365", "Betfair", "Betway", "BigBasket", "BigPay", "Bitget", "BitMart", "Bitpanda",
    "BlaBlaCar Daily", "Blinkit", "Blueground", "Bolt Food", "BookMyShow", "Brex", "Bukalapak", "Bunq", "Byju's", "C6 Bank",
    "CaixaBank", "Calendly", "Canada Post", "CapCut", "Carrefour", "Carvana", "Cdiscount", "Cebu Pacific", "CelcomDigi", "Chipper Cash",
    "CIMB", "Cineplex", "Clearpay", "CoinDCX", "CoinSwitch", "Comcast", "Commbank", "Converge", "Coupang", "Cred",
    "Credit Karma", "Curve", "Dailymotion", "DBS", "Deliveroo Plus", "Deutsche Bank", "Digi", "Diners Club", "Discord Nitro", "Dlocal",
    "Domino's", "Dunzo", "Easypaisa", "EasyTaxi", "Edenred", "Emirates", "Eneba", "Etsy Seller", "Fampay", "Fashion Nova",
    "Fawry", "FBS", "Fetch Rewards", "Foodora", "GCash Jr", "Getir", "Globe", "Gmarket", "GoFundMe", "GoTo",
    "GrabPay", "Grameenphone", "Greenlight", "Grofers", "Groupon", "Gumtree", "Halan", "HDFC Securities", "Heetch", "Hopper",
    "Hugos", "HungerStation", "IC Markets", "IDFC Bank", "IFood", "IndiGo", "Indomaret", "InPost", "Instacart", "Investec",
    "Itaú", "Jenius", "JetBlue", "Jiji", "JioMart", "Jumia", "KakaoBank", "KakaoPay", "Kaspi", "KFC",
    "Klarna", "Klook", "Konga", "KrisFlyer", "Kuda Bank", "Lalamove", "LBC Express", "Lemonade", "Lenskart", "Lidl",
    "LivU", "Luno", "Lycamobile", "M-Pesa Kenya", "M-Pesa Tanzania", "M-Pesa Mozambique", "M-Pesa Ghana", "M-Pesa Lesotho", "M-Pesa DRC", "Mashreq",
    "Maxis", "McDonald's", "Mercari", "Mercado Pago", "Miro Board", "Mobile Legends", "MoMo", "Monese", "MoneyLion", "Mukuru",
    "Myntra Insider", "Naver", "Naver Pay", "Nedbank", "NoBroker", "Noon Food", "Nubank Mexico", "OCBC", "Octopus", "Ola Money",
    "Ooredoo Money", "OpenSea", "Orange Cash", "OTP Bank", "Paddy Power", "PagBank", "Paymaya", "Paysera", "Paystack", "Peach Payments",
    "Pepperfry", "Pinduoduo", "Pix", "PlayerAuctions", "PUBG Mobile", "Qatar Airways", "QNB", "Quikr", "Rakuten Pay", "RappiPay",
    "Rapyd", "Rebtel", "RedBus", "Remitly Passbook", "Revolut Business", "Ria Money Transfer", "Riyad Bank", "SadaPay", "Safaricom", "Saks",
    "Salla", "Sberbank", "Sezzle", "Shahid", "Shipt", "Singtel", "Skrill Money Transfer", "Smart", "SoFi", "Southwest",
    "Splitwise", "Standard Bank", "Starzplay", "Stash", "Step", "Subito", "Sun NXT", "Supercell", "Swvl", "Tabby",
    "Taobao", "Tap Payments", "Tata CLiQ", "TBC Bank", "Telkomsel", "Tesco", "TheFork", "Thunes", "TikTok Shop", "Tinkoff",
    "Tokopedia", "Toss", "Touch n Go", "TransferGo", "TrueMoney", "Turo", "U Bank", "U Mobile", "Ualá", "Udaan",
    "Uphold", "USAA", "Vinted Pro", "Virgin Money", "Vodacom", "Voi", "Walmart MoneyCard", "WeBank", "WebMoney", "WeTransfer",
    "Wildberries", "Wizz Air", "WorldRemit Wallet", "Xendit", "Xero", "Yape", "Yemeksepeti", "Yoco", "Zalando", "Zelle Pay",
    "ZenBusiness", "Zenefits", "Zoho", "Zomato Gold", "Zopa", "Zynga", "2Checkout", "99acres", "99designs", "1688",
    "Abu Dhabi Commercial Bank", "ADCB", "Ajio", "Akulaku", "Alibaba Cloud", "Amazon Seller", "Amex", "An Post",
    "Atom Bank", "AU Bank", "Axis Direct", "Bajaj Markets", "Bandcamp", "Bank Al Bilad", "Bank Muscat", "Bank of Baroda",
    "Bank of India", "Bank of Montreal", "Bank of the Philippine Islands", "Bank of Scotland", "Banque Misr", "BBVA",
    "BeReal", "BharatPe", "BharatPe Merchant", "Bitso", "Blue Nile", "Boat", "Boursorama", "BPI", "Braintree",
    "Bread Financial", "Bright Money", "Bunq Business", "CAIXA", "CarDekho", "Cars24", "Cash App Taxes", "Cathay Pacific",
    "Celcoin", "Chime Card", "Citibank", "City Union Bank", "ClearTax", "CleverTap", "Coinhako", "CoinSpot", "Colombia Movil",
    "Comdirect", "CommSec", "Coolblue", "Costa Coffee", "Cricket Wireless", "Crypto.com Onchain", "CSGOEmpire", "CTBC Bank",
    "Current", "Curve Business", "Dabble", "DailyPay", "Dave", "Decathlon", "DeepL", "Dell", "Despegar", "Deutsche Telekom",
    "DigiBank", "Discord Developer", "Disney Plus Hotstar", "Dollar General", "Dollar Tree", "Dream11", "Dubai Islamic Bank",
    "Dutch Bros", "E*TRADE", "EasyPark", "Ebay Kleinanzeigen", "Ecobank", "Edelweiss", "EE", "Egypt Post", "El Corte Ingles",
    "Emirates NBD", "Enjoei", "Entropay", "Epic Games Store", "Equity Bank", "Etsy Checkout", "Eurobank", "Exness", "FabFitFun",
    "FairMoney", "FamilyMart", "FanDuel", "Fanatics", "Farfetch Access", "FastSpring", "Fever", "Fidelity NetBenefits",
    "First Abu Dhabi Bank", "FirstBank", "Five Guys", "Flipkart SuperCoins", "FlyDubai", "FoodHub", "Forex.com", "Fortnite",
    "Found", "Foxtel", "Framer", "FreeCharge UPI", "FreshBooks", "Frontier Airlines", "G2A", "Galaxy Store", "GameStop",
    "Garena Free Fire", "Geekbuying", "Gener8", "GetResponse", "Glovo Business", "GMX Mail", "GoDaddy Pro", "Goldman Sachs",
    "GoodRx", "Google Fi", "Google One", "Grab Driver", "Grab Merchant", "Green Dot", "Gumroad", "H&M Member", "Halifax",
    "Hamleys", "Handy", "Harbor Freight", "Harrods", "HBL", "HelloFresh", "Helo", "Hero FinCorp", "Hilton Honors",
    "HitPay", "Holafly", "Home Credit", "Honor Store", "Hotstar", "Houseparty", "HSBC UK", "Huawei Cloud", "HubSpot CRM",
    "Hulu Live", "HyperJar", "ICICI Direct", "ID.me", "iHerb", "IKEA Family", "Imo Beta", "IndusInd Bank", "Infomaniak",
    "Ingram Micro", "InstaPay", "Intuit", "Investing.com", "iPay88", "IQ Option", "Isbank", "Jazz World", "JD Sports",
    "Jet2", "JioSaavn Pro", "JumiaPay", "JustGiving", "Kakao Games", "Kasikorn Bank", "KFC App", "Kick", "Kiwi.com",
    "Klook Travel", "Kmart", "Kohls", "Kotak Securities", "KPN", "Krisp", "KuCoin Pay", "Lazada Wallet", "Leboncoin",
    "Lemon8", "Lenskart Pro", "Lidl Plus", "Lightning Network", "Lime", "Linode", "Lloyds Bank", "LocalBitcoins", "LottieFiles",
    "Lowes Pro", "Lufthansa", "Luminor", "Lyft Pink", "Macy's", "Magic Eden", "MakeMyTrip", "Malaysia Airlines", "Mango",
    "MapmyIndia", "Marriott Bonvoy", "Mashreq Neo", "Mastercard Send", "Max Fashion", "McDelivery", "MediaMarkt", "Meesho Supplier",
    "Mercado Libre Seller", "Meta Business", "Metro Bank", "MeWe", "Microsoft Rewards", "Midtrans", "Milanote", "Mint Mobile",
    "Miravia", "Mistplay", "Mixpanel", "Mobikwik Zip", "Mobile.de", "Mobily", "Modanisa", "Mollie", "MoneyGram Online",
    "Monzo Business", "Movistar", "MrQ", "Municipal Bank", "My11Circle", "Myntra Fashion", "N26 You", "Namshi", "National Bank of Egypt",
    "Naver Cloud", "Navy Federal", "Nebula", "Nequi", "NetBank", "Neteller VIP", "Newegg", "Nextdoor", "Nike Membership",
    "NordVPN", "Nordea", "Nova Poshta", "Now TV", "NRK", "Nubank Ultravioleta", "Nutaku", "Nvidia", "O2", "Ocado",
    "OfferUp", "OkCoin", "Old Navy", "Omio", "One NZ", "OnePlus Store", "OnlyFans", "OpenPhone", "Optus", "Oriflame",
    "Origin Energy", "OVO Energy", "OXXO", "Paddy Power Betfair", "PagSeguro", "Palace Skateboards", "Pampers Club", "Panasonic",
    "Papa John's", "Paramount+", "ParkMobile", "Pathao", "Paybis", "PayBy", "PayFit", "Payhip", "PayPal Business", "PayPay",
    "Paysafe", "Paysend", "Payslip", "PC Financial", "Peloton App", "People's Postcode Lottery", "Perplexity Pro", "Petco",
    "PetSmart", "Philips Hue", "PhonePe Business", "PicPay Empresas", "Pizza Hut", "Plaid", "Playtika", "Pockit", "PokerStars",
    "Polkadot", "Popeyes", "Poshmark Seller", "Postbank", "PostFinance", "Postmates Unlimited", "Powerball", "Premier League",
    "Preply", "Primark", "Prime Now", "Probo", "Proton VPN", "PUBG New State", "Puma", "PureGym", "Qatar ID", "Qiwi",
    "QuikTrip", "Quora Digest", "Rabobank", "Rappi Turbo", "Razer Gold", "RBC Direct", "Real Debrid", "Reddit Premium",
    "Remitano", "Renault", "Replit", "Revolut Junior", "Ria App", "Ring", "Riot Mobile", "Rite Aid", "Roam Mobility",
    "Robinhood Crypto", "Roblox Premium", "Roku", "Royal Caribbean", "Rumble", "RummyCircle", "RushCard", "Ryanair",
    "Sainsbury's", "Samsung Pay", "Santander UK", "Saudi Airlines", "SBI Card", "Scalable Capital", "Schwab Mobile", "Scopely",
    "SeaBank", "Seamless", "SHEIN Club", "Shell Go+", "Shopee Seller", "Shopify Balance", "Showmax", "SignalHire", "Singpass",
    "SiriusXM", "Sixt", "Skrill Business", "Sky Bet", "Sky Mobile", "Skyscanner Flights", "Smart Fit", "Smiles", "Snap Finance",
    "SnapPay", "Snoop", "Societe Generale", "SoftBank", "Sonos", "Sony PlayStation", "SoundHound", "Southwest Rapid Rewards",
    "Spartan Race", "Spectrum Mobile", "Spotify Premium", "Sprinklr", "Square Cash", "Stan", "Standard Chartered", "Starling Kite",
    "Starlink", "Steam Guard", "StockX Seller", "Stripe Atlas", "Subway", "SumUp", "Sunrise", "Superdrug", "Surfshark",
    "Swiggy Instamart", "Swisscom", "Syfe", "Synapse", "T-Mobile Money", "Taco Bell", "Tada", "Taj Hotels", "Takealot",
    "Talabat Pro", "Tango", "TapTap", "Target Circle", "TaskRabbit", "Tata Neu", "TaxAct", "Taxfix", "TD Ameritrade",
    "Tele2", "Telegram Premium", "Telus", "Tempo", "Tesco Clubcard", "Tether", "Thai Airways", "The Body Shop", "The Guardian",
    "The Home Depot Pro", "The North Face", "The RealReal", "The Weather Channel", "Thermomix", "ThredUp", "Three UK",
    "TicketSwap", "Tide Business", "TikTok Lite", "TikTok for Business", "Tim Hortons", "Tinder Gold", "Titan", "Toast POS",
    "Tokyo Gas", "TomTom", "Topshop", "TorFX", "Total Wine", "TouchBank", "Trade Republic", "Trading 212", "Trainline",
    "TransferMate", "Traveloka", "Treasury Direct", "Trend Micro", "Trivago", "TronLink", "TrueBill", "Trust Wallet",
    "Turkish Airlines", "Turkcell", "Twitch Prime", "Uber One", "Uber Pro", "Udacity Nanodegree", "UFC Fight Pass", "Ulta Beauty",
    "Under Armour", "UniCredit", "United Airlines", "UnitedHealth", "Unity", "Unreal Engine", "Urban Outfitters", "US Mobile",
    "USDT Wallet", "Vanguard", "Varo Believe", "Vattenfall", "Veeam", "Venmo Business", "Vercel Pro", "Victoria's Secret",
    "Vimeo", "Virgin Atlantic", "Virgin Media", "Visa Checkout", "Vistara", "Viva Wallet", "Vivo Pay", "Vodafone Cash",
    "Volkswagen", "Vrbo Host", "Walgreens", "Walmart Plus", "Warby Parker", "Warner Bros Discovery", "Wayfair", "WeChat Pay",
    "Weee!", "Wells Fargo Mobile", "Westpac", "WhatsApp Business", "WhiteBIT", "Whole Foods", "Wickes", "Wild Rift",
    "William Hill", "Windscribe", "Wingstop", "Wish Local", "Wolt Drive", "Woodforest", "WorldFirst", "Wunderkind", "Xbox Game Pass",
    "Xfinity", "Xiaomi Pay", "Yahoo Finance", "Yalla", "Yandex Market", "Yandex Taxi", "Yandex Zen", "Yelp Guest Manager",
    "Yonder", "YouGov", "YouTrip", "Yubo", "Zalando Lounge", "Zara Home", "Zaxby's", "Zenly", "Zeta", "Zip Co",
    "ZipRecruiter Employer", "Zivame", "Zoom Workplace", "Zurich Insurance",
)
